# Generated by Django 5.0 on 2024-01-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenciler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adSoyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('hakkinda', models.TextField(max_length=300)),
                ('resim', models.FileField(upload_to='profilResim')),
            ],
        ),
    ]
