# Generated by Django 5.0 on 2024-01-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Urun İsmi')),
                ('aciklama', models.TextField(max_length=500)),
                ('fiyat', models.IntegerField(default=0)),
            ],
        ),
    ]
